#!/usr/bin/env python3
"""
Markdown Reporter - Generate Human-Readable Reports

Generates Markdown reports with:
- Summary statistics
- Tables with selected cases
- Links to visualization files
- Easy to read and share

Perfect for:
- Documentation
- Project reports
- GitHub README updates
- Quick review of results
"""

from pathlib import Path
from typing import Any, Dict, List
from datetime import datetime
import pandas as pd

from .base_reporter import BaseReporter


class MarkdownReporter(BaseReporter):
    """
    Generate Markdown reports with tables and statistics.

    Output format: GitHub-flavored Markdown
    Compatible with: GitHub, GitLab, VS Code, most markdown viewers

    Example:
        reporter = MarkdownReporter(title="Visualization Analysis Report")
        reporter.generate(analysis_data, 'report.md')
    """

    def __init__(self, title: str = "Visualization Report", include_toc: bool = True):
        """
        Initialize Markdown reporter.

        Args:
            title: Report title
            include_toc: Whether to include table of contents
        """
        super().__init__(title)
        self.include_toc = include_toc

    def generate(self, data: Dict[str, Any], output_path: Path) -> bool:
        """
        Generate Markdown report.

        Args:
            data: Dict with report data:
                - 'summary': Dict with summary statistics
                - 'detection_errors': DataFrame with detection errors
                - 'classification_errors': DataFrame with classification errors
                - 'metadata': Any additional metadata
            output_path: Path for output Markdown file

        Returns:
            True if successful, False otherwise
        """
        try:
            output_path = Path(output_path)
            self.ensure_output_dir(output_path)

            with open(output_path, 'w', encoding='utf-8') as f:
                # Header
                f.write(f"# {self.title}\n\n")
                f.write(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
                f.write("---\n\n")

                # Table of Contents
                if self.include_toc:
                    f.write(self._generate_toc(data))
                    f.write("\n---\n\n")

                # Summary Section
                if 'summary' in data:
                    f.write(self._generate_summary(data['summary']))
                    f.write("\n")

                # Detection Errors Section
                if 'detection_errors' in data and not data['detection_errors'].empty:
                    f.write(self._generate_detection_section(data['detection_errors']))
                    f.write("\n")

                # Classification Errors Section
                if 'classification_errors' in data and not data['classification_errors'].empty:
                    f.write(self._generate_classification_section(data['classification_errors']))
                    f.write("\n")

                # Training Curves Section
                if 'training_curves' in data:
                    f.write(self._generate_training_curves_section(data['training_curves']))
                    f.write("\n")

                # Footer
                f.write("---\n\n")
                f.write("*Report generated by visualization pipeline*\n")

            print(f"[SAVED] Markdown report → {output_path}")
            return True

        except Exception as e:
            print(f"[ERROR] Failed to generate Markdown: {e}")
            import traceback
            traceback.print_exc()
            return False

    def _generate_toc(self, data: Dict) -> str:
        """Generate table of contents."""
        toc = "## Table of Contents\n\n"
        toc += "1. [Summary](#summary)\n"

        if 'detection_errors' in data and not data['detection_errors'].empty:
            toc += "2. [Detection Errors](#detection-errors)\n"

        if 'classification_errors' in data and not data['classification_errors'].empty:
            toc += "3. [Classification Errors](#classification-errors)\n"

        if 'training_curves' in data:
            toc += "4. [Training Curves](#training-curves)\n"

        return toc

    def _generate_summary(self, summary: Dict) -> str:
        """Generate summary section."""
        md = "## Summary\n\n"

        # Overall stats
        if 'experiment_dir' in summary:
            md += f"**Experiment:** `{summary['experiment_dir']}`\n\n"

        if 'total_datasets' in summary:
            md += f"- **Datasets:** {summary['total_datasets']}\n"

        if 'total_models' in summary:
            md += f"- **Models:** {summary['total_models']}\n"

        if 'total_visualizations' in summary:
            md += f"- **Total Visualizations:** {summary['total_visualizations']}\n"

        if 'total_selected' in summary:
            md += f"- **Selected Cases:** {summary['total_selected']}\n"

        md += "\n"

        # Per-dataset stats
        if 'datasets' in summary:
            md += "### Per-Dataset Statistics\n\n"
            md += "| Dataset | Detection Models | Classification Models | Visualizations |\n"
            md += "|---------|------------------|----------------------|----------------|\n"

            for ds_name, ds_stats in summary['datasets'].items():
                md += f"| {ds_name} | {ds_stats.get('n_detection', 0)} | "
                md += f"{ds_stats.get('n_classification', 0)} | "
                md += f"{ds_stats.get('n_visualizations', 0)} |\n"

            md += "\n"

        return md

    def _generate_detection_section(self, detection_df: pd.DataFrame) -> str:
        """Generate detection errors section."""
        md = "## Detection Errors\n\n"

        # Group by error category
        if 'error_category' in detection_df.columns:
            for category in detection_df['error_category'].unique():
                category_df = detection_df[detection_df['error_category'] == category]

                md += f"### {category}\n\n"
                md += f"**Count:** {len(category_df)} cases\n\n"

                # Table with top cases
                md += "| Image | FP | FN | Confidence | Score | Path |\n"
                md += "|-------|----|----|------------|-------|------|\n"

                for _, row in category_df.head(10).iterrows():
                    img_name = row.get('image_name', 'N/A')
                    fp = row.get('n_false_positives', 0)
                    fn = row.get('n_false_negatives', 0)
                    conf = row.get('avg_confidence', 0)
                    score = row.get('paper_score', 0)
                    img_file = Path(row.get('image_file', '')).name

                    md += f"| {img_name} | {fp} | {fn} | {conf:.3f} | {score} | `{img_file}` |\n"

                md += "\n"

        return md

    def _generate_classification_section(self, classification_df: pd.DataFrame) -> str:
        """Generate classification errors section."""
        md = "## Classification Errors\n\n"

        # Group by error category
        if 'error_category' in classification_df.columns:
            for category in classification_df['error_category'].unique():
                category_df = classification_df[classification_df['error_category'] == category]

                md += f"### {category}\n\n"
                md += f"**Count:** {len(category_df)} cases\n\n"

                # Table with top cases
                md += "| Image | Boxes | Correct | Incorrect | Accuracy | Confidence | Score |\n"
                md += "|-------|-------|---------|-----------|----------|------------|-------|\n"

                for _, row in category_df.head(10).iterrows():
                    img_name = row.get('image_name', 'N/A')
                    n_boxes = row.get('n_boxes', 0)
                    n_correct = row.get('n_correct', 0)
                    n_incorrect = row.get('n_incorrect', 0)
                    accuracy = row.get('accuracy', 0)
                    conf = row.get('avg_confidence', 0)
                    score = row.get('paper_score', 0)

                    md += f"| {img_name} | {n_boxes} | {n_correct} | {n_incorrect} | "
                    md += f"{float(accuracy):.3f} | {float(conf):.3f} | {score} |\n"

                md += "\n"

        return md

    def _generate_training_curves_section(self, training_info: Dict) -> str:
        """Generate training curves section."""
        md = "## Training Curves\n\n"

        if 'generated_figures' in training_info:
            md += f"**Generated Figures:** {training_info['generated_figures']}\n\n"

        if 'output_dir' in training_info:
            md += f"**Location:** `{training_info['output_dir']}`\n\n"

        if 'plot_types' in training_info:
            md += f"**Plot Types:** {', '.join(training_info['plot_types'])}\n\n"

        return md
