classes:
  0: "P_falciparum"
  1: "P_vivax"
  2: "P_malariae"
  3: "P_ovale"
  4: "Mixed_infection"
  5: "Uninfected"

colors:  # BGR format
  0: [255, 0, 0]       # Blue
  1: [0, 255, 0]       # Green
  2: [0, 0, 255]       # Red
  3: [255, 255, 0]     # Cyan
  4: [255, 0, 255]     # Magenta
  5: [128, 128, 128]   # Gray
