datasets:
  nih:
    name: "NIH Malaria Dataset"
    url: "https://www.cell.com/cell/fulltext/S0092-8674(18)30488-7"
    path: "data/raw/NIH"
    classes: ["P_falciparum", "P_vivax", "P_malariae", "P_ovale", "Mixed_infection", "Uninfected"]
    description: "Cell segmentation with species classification"

  mp_idb:
    name: "MP-IDB Malaria Parasite Image Database"
    url: "https://www.cs.cityu.edu.hk/~abchan/mp-idb/"
    path: "data/raw/MP_IDB"
    classes: ["Infected", "Uninfected"]
    description: "Binary classification dataset"

  bbbc041:
    name: "BBBC041 Malaria Dataset"
    url: "https://bbbc.broadinstitute.org/BBBC041"
    path: "data/raw/BBBC041"
    classes: ["Parasitized", "Uninfected"]
    description: "Broad Institute dataset"

  plasmo_id:
    name: "PlasmoID Dataset"
    url: "https://github.com/sbargoti/PlasmoID-Malaria-Parasite-Classification"
    path: "data/raw/PlasmoID"
    classes: ["P_falciparum", "P_vivax", "P_malariae", "P_ovale"]
    description: "Multi-species classification"

  iml:
    name: "IML Malaria Dataset"
    url: "https://www.kaggle.com/datasets/iarunava/cell-images-for-detecting-malaria"
    path: "data/raw/IML"
    classes: ["Parasitized", "Uninfected"]
    description: "Kaggle malaria detection dataset"

  uganda:
    name: "Uganda Malaria Dataset"
    url: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7020031/"
    path: "data/raw/Uganda"
    classes: ["Infected", "Uninfected"]
    description: "Field study dataset from Uganda"

# Target classes for unified dataset
target_classes:
  - "P_falciparum"
  - "P_vivax"
  - "P_malariae"
  - "P_ovale"
  - "Mixed_infection"
  - "Uninfected"

# Class mapping from source to target
class_mapping:
  "Infected": "Mixed_infection"
  "Parasitized": "Mixed_infection"
  "Uninfected": "Uninfected"
  "P_falciparum": "P_falciparum"
  "P_vivax": "P_vivax"
  "P_malariae": "P_malariae"
  "P_ovale": "P_ovale"

# Processed datasets for training
processed_datasets:
  detection_multispecies:
    type: "detection"
    path: "data/detection_multispecies/dataset.yaml"
    description: "Multi-species malaria detection dataset"
    classes: 1
    expected_structure:
      - "train/images"
      - "train/labels"
      - "val/images"
      - "val/labels"

  detection_fixed:
    type: "detection"
    path: "data/detection_fixed/dataset.yaml"
    description: "Fixed detection dataset"
    classes: 1

  classification_multispecies:
    type: "classification"
    path: "data/classification_multispecies"
    description: "Multi-species malaria classification dataset"
    classes: 4
    class_names: ["P_falciparum", "P_vivax", "P_malariae", "P_ovale"]
    expected_structure:
      - "P_falciparum"
      - "P_vivax"
      - "P_malariae"
      - "P_ovale"

  classification_crops:
    type: "classification"
    path: "data/classification_crops"
    description: "Classification crops dataset"
    classes: 4

# Validation requirements
validation:
  min_images_per_class: 10
  required_splits: ["train", "val"]
  supported_formats: [".jpg", ".png", ".jpeg"]